services:
  ollama:
    build:
      dockerfile: dockerfiles/ollama
      context: ./
    environment:
      - LLM_MODEL=${LLM_MODEL}
    entrypoint: "/tmp/run-ollama.sh"
    healthcheck:
      test: ollama --version || exit 1
      interval: 60s
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build:
      context: .
      dockerfile: dockerfiles/python
    environment:
      - LLM_MODEL=${LLM_MODEL}
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    restart: always
