version: '3.8'

services:
  ollama:
    build:
      dockerfile: dockerfiles/ollama
      context: ./
    container_name: ollama
    environment:
      - LLM_MODEL=${LLM_MODEL}
    entrypoint: "/tmp/run-ollama.sh"
    tty: true
    healthcheck:
      test: ollama --version || exit 1
      interval: 10s
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build:
      context: .
      dockerfile: dockerfiles/python
    container_name: python_app
    environment:
      - LLM_MODEL=${LLM_MODEL}
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - ollama
    restart: always

networks:
  default:
